version: '3.9'

services:
  maskdino:
    build: .
    runtime: nvidia
    stdin_open: true
    tty: true
    ipc: host
    volumes:
      - ..:/workspace/MaskDINO
    ulimits:
      memlock: -1
      stack: 67108864
